// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "codinghobby-20181007165150--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1yuy4kskpckp2.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:c1af9dc1-1bb3-414c-9eb8-da5d6d0cebcf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r8MVhf5mp",
    "aws_user_pools_web_client_id": "19qhklt9887nijta4p2ds0p37r"
};


export default awsmobile;
